"""Utility functions for symmetric encryption using Fernet."""

from cryptography.fernet import Fernet, InvalidToken


def generate_key() -> bytes:
    """Generate a secure Fernet encryption key."""
    return Fernet.generate_key()


def encrypt_message(key: bytes, plaintext: str) -> str:
    """Encrypt plaintext using the provided Fernet key.

    Args:
        key: The bytes key generated by generate_key().
        plaintext: The message that should be encrypted.

    Returns:
        A base64-encoded token string containing the encrypted ciphertext.
    """
    if not key:
        raise ValueError("Encryption key is required.")
    if plaintext is None:
        raise ValueError("Plaintext cannot be empty.")

    fernet = Fernet(key)
    token = fernet.encrypt(plaintext.encode("utf-8"))
    return token.decode("utf-8")


def decrypt_message(key: bytes, token: str) -> str:
    """Decrypt a Fernet token back to plaintext.

    Args:
        key: The bytes key used to decrypt the token.
        token: The encrypted token string returned by encrypt_message.

    Returns:
        The original plaintext string.
    """
    if not key:
        raise ValueError("Decryption key is required.")
    if not token:
        raise ValueError("Encrypted text cannot be empty.")

    fernet = Fernet(key)
    try:
        plaintext_bytes = fernet.decrypt(token.encode("utf-8"))
        return plaintext_bytes.decode("utf-8")
    except InvalidToken as error:
        raise ValueError("Invalid token or incorrect key.") from error
